"""Choose location from input file."""

from enum import Enum

from source.scrape_webpages.scrape import find_web_link


class Location(Enum):
    ABERPORTH = find_web_link("ABERPORTH")
    ARMAGH = find_web_link("ARMAGH")
    BALLYPATRICK_FOREST = find_web_link("BALLYPATRICK_FOREST")
    BRADFORD = find_web_link("BRADFORD")
    BRAEMAR_NO_2 = find_web_link("BRAEMAR_NO_2")
    CAMBORNE = find_web_link("CAMBORNE")
    CAMBRIDGE_NIAB = find_web_link("CAMBRIDGE_NIAB")
    CARDIFF_BUTE_PARK = find_web_link("CARDIFF_BUTE_PARK")
    CHIVENOR = find_web_link("CHIVENOR")
    CWMYSTWYTH = find_web_link("CWMYSTWYTH")
    DUNSTAFFNAGE = find_web_link("DUNSTAFFNAGE")
    DURHAM = find_web_link("DURHAM")
    EASTBOURNE = find_web_link("EASTBOURNE")
    ESKDALEMUIR = find_web_link("ESKDALEMUIR")
    HEATHROW = find_web_link("HEATHROW")
    HURN = find_web_link("HURN")
    LERWICK = find_web_link("LERWICK")
    LEUCHARS = find_web_link("LEUCHARS")
    LOWESTOFT_MONCKTON_AVENUE = find_web_link("LOWESTOFT_MONCKTON_AVENUE")
    MANSTON = find_web_link("MANSTON")
    NAIRN_DRUIM = find_web_link("NAIRN_DRUIM")
    NEWTON_RIGG = find_web_link("NEWTON_RIGG")
    OXFORD = find_web_link("OXFORD")
    PAISLEY = find_web_link("PAISLEY")
    RINGWAY = find_web_link("RINGWAY")
    ROSS_ON_WYE = find_web_link("ROSS_ON_WYE")
    SHAWBURY = find_web_link("SHAWBURY")
    SHEFFIELD = find_web_link("SHEFFIELD")
    SOUTHAMPTON_MAYFLOWER_PARK = find_web_link("SOUTHAMPTON_MAYFLOWER_PARK")
    STORNOWAY_AIRPORT = find_web_link("STORNOWAY_AIRPORT")
    SUTTON_BONINGTON = find_web_link("SUTTON_BONINGTON")
    TIREE = find_web_link("TIREE")
    VALLEY = find_web_link("VALLEY")
    WADDINGTON = find_web_link("WADDINGTON")
    WHITBY = find_web_link("WHITBY")
    WICK_AIRPORT = find_web_link("WICK_AIRPORT")
    YEOVILTON = find_web_link("YEOVILTON")
